[tasks.autoadd]
command = "git"
args = ["add", "./src/bin/${@}.rs"]

[tasks.autocommit]
dependencies = ["autoadd"]
command = "git"
args = ["commit", "-m", "autocommit on submission (./src/bin/${@}.rs)"]

[tasks.run]
command = "cargo"
args = ["run", "--bin", "${@}"]

[tasks.test]
command = "cargo"
args = ["atcoder", "test", "${@}"]

[tasks.expand]
script = "expand_mod --bin ${@}"

[tasks.submit-force]
dependencies = ["expand", "autocommit"]
command = "cargo"
args = ["atcoder", "submit", "${@}", "--force"]

[tasks.submit]
dependencies = ["expand", "autoadd"]
script = '''
contest_id=$(grep "name" Cargo.toml | sed -e 's/name = //g' | sed -e 's/\"//g')
submit_result=$(script -efq /dev/null -c "cargo atcoder submit ${@}" | tee /dev/tty)

is_test_success=$(echo $submit_result | grep "FAILED" | wc -l)

if [ $is_test_success -eq 0 ]; then
    
    is_submit_success=$(echo $submit_result | grep -e "Wrong Answer" -e "CE" -e "TLE" | wc -l)

    if [ $is_submit_success -eq 0 ]; then
        commit_message="AC!! autocommit in ${contest_id}-${@}"
    else
        commit_message="WA;; autocommit in ${contest_id}-${@}"
    fi
else
    commit_message="TEST FAILED. autocommit in ${contest_id}-${@}"
fi

git add "./src/bin/${@}.rs"
git commit -m "$commit_message"
'''